version: "3.9"
services:
  api:
    image: donkeyhott/ekbtrees-api:latest
    environment:
      DATASOURCE_URL: "jdbc:postgresql://postgres:5432/ectm"
      S3_HOST: "http://s3:9090"
      SHOW_SQL: "true"
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
    - "8080:8080"
    - "5005:5005"
    depends_on:
      - postgres
      - s3
      - auth

  auth:
    image: donkeyhott/ekbtrees-auth:latest
    environment:
      DATASOURCE_URL: "jdbc:postgresql://postgres:5432/ectm"
      SHOW_SQL: "true"
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    ports:
      - "8081:8081"
      - "5006:5006"
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:12-3.0-alpine
    environment:
      POSTGRES_DB: "ectm"
      POSTGRES_USER: "ectm"
      POSTGRES_PASSWORD: "ectm"
    ports:
      - "${DB_PORT:-54325}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  s3:
    image: adobe/s3mock:2.1.29
    environment:
      initialBuckets: "ectm"
    ports:
    - "9090:9090"
    - "9191:9191"

volumes:
  dbdata:
